#!/usr/bin/env python

bld.SAMBA3_SUBSYSTEM('PARAM_UTIL',
                     source='util.c',
                     deps='talloc')

bld.SAMBA3_SUBSYSTEM('LOADPARM_CTX',
                     source='loadparm_ctx.c',
                     deps='''talloc smbconf''')

bld.SAMBA_GENERATOR('s3_param_proto_h',
                    source= '../../script/generate_param.py ../../docs-xml/smbdotconf/parameters.all.xml',
                    target='param_proto.h',
                    group='build_source',
                    rule='${PYTHON} ${SRC[0].abspath(env)} --file ${SRC[1].abspath(env)} --output ${TGT} --mode=S3PROTO')

pytalloc_util = bld.pyembed_libname('pytalloc-util')
pyparam_util = bld.pyembed_libname('pyparam3_util')
libpython = bld.pyembed_libname('LIBPYTHON')

bld.SAMBA3_PYTHON('pys3param',
                  source='pyparam.c',
                  deps='smbconf %s' % pyparam_util,
                  public_deps=' '.join(['samba-hostconfig', pytalloc_util, 'talloc']),
                  realname='samba/samba3/param.so')

bld.SAMBA3_SUBSYSTEM(pyparam_util,
                source='pyparam_util.c',
                deps='%s samba-hostconfig %s' % (libpython, pytalloc_util),
                pyext=True,
                enabled=bld.PYTHON_BUILD_IS_ENABLED()
                )

bld.SAMBA3_SUBSYSTEM('param_service',
                     source='service.c',
                     deps = 'USER_UTIL smbconf')

bld.SAMBA3_BINARY('test_lp_load',
                 source='test_lp_load.c',
                 deps='''
                 talloc
                 smbconf
                 CMDLINE_S3
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS gse secrets3 cli_cldap MESSAGING smbldap smbldaphelper pdb printing_migrate samba-passdb libcli_netlogon3 libsmb cli_spoolss ads
samba-util popt CMDLINE_S3 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug talloc_report_printf dcerpc-pkt-auth krb5samba authkrb5 krb5samba common_auth npa_tstream msrpc3 auth libcli_lsa3  netapi trusts_util
''',
                 install=False)
