#!/usr/bin/env python

bld.SAMBA_LIBRARY('cliauth',
                  source='',
                  deps='MSRPC_PARSE LIBCLI_AUTH COMMON_SCHANNEL PAM_ERRORS SPNEGO_PARSE krb5samba samba-errors NTLM_CHECK UTIL_LSARPC',
                  private_library=True,
                  grouping_library=True)

bld.SAMBA_SUBSYSTEM('MSRPC_PARSE',
	source='msrpc_parse.c',
	deps='talloc'
	)

bld.SAMBA_SUBSYSTEM('NTLM_CHECK',
                    source='ntlm_check.c',
                    deps = 'talloc LIBCLI_AUTH'
                    )

bld.SAMBA_SUBSYSTEM('LIBCLI_AUTH',
	source='credentials.c session.c smbencrypt.c smbdes.c',
	public_deps='MSRPC_PARSE gnutls GNUTLS_HELPERS util_str_escape',
	public_headers='credentials.h:domain_credentials.h'
	)


bld.SAMBA_SUBSYSTEM('COMMON_SCHANNEL',
	source='schannel_state_tdb.c',
	deps='dbwrap util_tdb samba-hostconfig NDR_NETLOGON'
	)

bld.SAMBA_SUBSYSTEM('NETLOGON_CREDS_CLI',
        source='netlogon_creds_cli.c',
        deps='''
        dbwrap
        util_tdb
        tevent-util
        samba-hostconfig
        gensec
        RPC_NDR_NETLOGON
        NDR_NETLOGON
        '''
        )

bld.SAMBA_SUBSYSTEM('PAM_ERRORS',
	source='pam_errors.c',
	deps='talloc'
	)

bld.SAMBA_SUBSYSTEM('SPNEGO_PARSE',
                    source='spnego_parse.c',
                    deps='asn1util')

bld.SAMBA_BINARY(
        'test_ntlm_check',
        source='tests/ntlm_check.c',
        deps='''
             NTLM_CHECK
             CREDENTIALS_NTLM
             samba-credentials
             cmocka
             talloc
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS
samba-util popt CMDLINE_S3 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug talloc_report_printf dcerpc-pkt-auth krb5samba authkrb5 krb5samba
''',
        for_selftest=True
    )

bld.SAMBA_BINARY('test_rc4_passwd_buffer',
                 source='tests/test_rc4_passwd_buffer.c',
                 deps='''
                      INIT_SAMR
                      LIBCLI_AUTH
                      cmocka
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS
samba-util popt CMDLINE_S3 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug talloc_report_printf dcerpc-pkt-auth krb5samba authkrb5 krb5samba
''',
                 for_selftest=True)

bld.SAMBA_BINARY('test_schannel',
                 source='tests/test_schannel.c',
                 deps='''
                      gensec
                      cmocka
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS
samba-util popt CMDLINE_S3 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug talloc_report_printf dcerpc-pkt-auth krb5samba authkrb5 krb5samba
''',
                 for_selftest=True)

bld.SAMBA_BINARY('test_gnutls',
                 source='tests/test_gnutls.c',
                 deps='''
                      gnutls
                      LIBCLI_AUTH
                      cmocka
                      samba-util
                      ''',
                 for_selftest=True)

bld.SAMBA_BINARY('test_encode_decode',
                 source='tests/test_encode_decode.c',
                 deps='''
                      LIBCLI_AUTH
                      cmocka
                      samba-util
                      ''',
                 for_selftest=True)
