#!/usr/bin/env python

bld.SAMBA3_SUBSYSTEM('fcn_wait',
                     source='fcn_wait.c',
                     deps='samba3core')

bld.SAMBA3_SUBSYSTEM('notifyd_db',
		     source='notifyd_entry.c notifyd_db.c',
                     deps='samba-debug dbwrap errors3')

bld.SAMBA3_SUBSYSTEM('notifyd',
		     source='notifyd.c',
                     deps='''
                         util_tdb
                         TDB_LIB
                         messages_util
                         notifyd_db
                     ''')

bld.SAMBA3_BINARY('notifyd-tests',
                  source='tests.c',
                  install=False,
                  deps='''
                       smbconf
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS gse  secrets3 cli_cldap MESSAGING smbldap smbldaphelper pdb printing_migrate samba-passdb libcli_netlogon3 libsmb cli_spoolss ads
samba-util popt CMDLINE_S3 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug talloc_report_printf dcerpc-pkt-auth krb5samba authkrb5 krb5samba common_auth npa_tstream msrpc3 auth libcli_lsa3  netapi trusts_util xattr_tdb
                  ''')

bld.SAMBA3_BINARY('notifydd',
                  source='notifydd.c',
                  install=False,
                  deps='''notifyd
                       smbconf
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS gse  secrets3 cli_cldap MESSAGING smbldap smbldaphelper pdb printing_migrate samba-passdb libcli_netlogon3 libsmb cli_spoolss ads
samba-util popt CMDLINE_S3 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug talloc_report_printf dcerpc-pkt-auth krb5samba authkrb5 krb5samba common_auth npa_tstream msrpc3 auth libcli_lsa3  netapi trusts_util xattr_tdb
                  ''')

TORTURE_NOTIFYD_SOURCE='test_notifyd.c'
TORTURE_NOTIFYD_DEPS='fcn_wait notifyd_db'

bld.SAMBA_MODULE('TORTURE_NOTIFYD',
	source=TORTURE_NOTIFYD_SOURCE,
	subsystem='smbtorture',
	init_function='torture_notifyd_init',
	deps=TORTURE_NOTIFYD_DEPS,
	internal_module=True,
	enabled=bld.PYTHON_BUILD_IS_ENABLED()
	)
