#!/usr/bin/env python


def build(bld):
    bld.SAMBA_LIBRARY('smb_transport',
        source='''
            read_smb.c
        ''',
        deps='LIBASYNC_REQ',
        public_deps='talloc tevent',
        private_library=True,
        private_headers='''
            read_smb.h
        ''',
        )

    bld.SAMBA_LIBRARY('cli_smb_common',
    source='''
           smb_signing.c
           smb_seal.c
           smb2_negotiate_context.c
           smb2_create_blob.c smb2_signing.c
           smb2_lease.c
           util.c
           smbXcli_base.c
           smb1cli_trans.c
           smb1cli_echo.c
           smb1cli_create.c
           smb1cli_session.c
           smb1cli_close.c
           smb1cli_write.c
           smb1cli_read.c
           smb2cli_session.c
           smb2cli_tcon.c
           smb2cli_create.c
           smb2cli_close.c
           smb2cli_read.c
           smb2cli_write.c
           smb2cli_flush.c
           smb2cli_set_info.c
           smb2cli_query_info.c
           smb2cli_notify.c
           smb2cli_query_directory.c
           smb2cli_ioctl.c
           smb2cli_echo.c
           tstream_smbXcli_np.c
    ''',
    deps='''
        LIBCRYPTO gnutls NDR_SMB2_LEASE_STRUCT samba-errors gensec krb5samba
        smb_transport GNUTLS_HELPERS
    ''',
    public_deps='talloc samba-util iov_buf',
    private_library=True,
    private_headers='''
                    smb_common.h
                    smb2_constants.h
                    smb_constants.h
                    smb_signing.h
                    smb_seal.h
                    smb2_create_blob.h
                    smb2_signing.h
                    smb2_lease.h
                    smb_util.h
                    smb_unix_ext.h
                    tstream_smbXcli_np.h
    ''',
    )

    bld.SAMBA_BINARY('test_smb1cli_session',
                     source='test_smb1cli_session.c',
                     deps='''cmocka cli_smb_common
POPT_SAMBA POPT_CREDENTIALS smbclient-raw param_options dcerpc
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS
samba-util popt POPT_SAMBA ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth winbind-client RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug 
''',
                     install=False)
