cp bin/cifsdd.exe /samba
cp bin/dbwrap_tool.exe /samba
cp bin/eventlogadm.exe /samba
cp bin/ldbadd.exe /samba
cp bin/default/lib/ldb/ldbdel.exe /samba
cp bin/ldbedit.exe /samba
cp bin/ldbmodify.exe /samba
cp bin/ldbrename.exe /samba
cp bin/ldbsearch.exe /samba
cp bin/mvxattr.exe /samba
cp bin/ndrdump.exe /samba
cp bin/net.exe /samba
cp bin/nmbd.exe /samba
cp bin/nmblookup.exe /samba
cp bin/oLschema2ldif.exe /samba
cp bin/pdbedit.exe /samba
cp bin/profiles.exe /samba
cp bin/regdiff.exe /samba
cp bin/regpatch.exe /samba
cp bin/regshell.exe /samba
cp bin/regtree.exe /samba
cp bin/rpcclient.exe /samba
cp bin/samba-regedit.exe /samba
cp bin/smbcacls.exe /samba
cp bin/smbclient.exe /samba
cp bin/smbcontrol.exe /samba
cp bin/smbcquotas.exe /samba
cp bin/smbd.exe /samba
cp bin/smbget.exe /samba
cp bin/smbpasswd.exe /samba
cp bin/smbspool.exe /samba
cp bin/smbstatus.exe /samba
cp bin/smbtree.exe /samba
cp bin/tdbbackup.exe /samba
cp bin/tdbdump.exe /samba
cp bin/tdbrestore.exe /samba
cp bin/tdbtool.exe /samba
cp bin/testparm.exe /samba
cp bin/wbinfo.exe /samba
cp bin/winbindd.exe /samba
