#!/usr/bin/env python

if bld.env.WITH_PTHREADPOOL:
    extra_libs=''

    # Link to librt if needed for clock_gettime()
    if bld.CONFIG_SET('HAVE_LIBRT'): extra_libs += ' rt'

    bld.SAMBA_SUBSYSTEM('PTHREADPOOL',
                         source='''pthreadpool.c
                                   pthreadpool_pipe.c
                                   pthreadpool_tevent.c
                                ''',
                         deps='pthread replace tevent-util' + extra_libs)
else:
    bld.SAMBA_SUBSYSTEM('PTHREADPOOL',
                         source='''pthreadpool_sync.c
                                   pthreadpool_pipe.c
                                   pthreadpool_tevent.c
                                ''',
                         deps='replace tevent-util')


bld.SAMBA_BINARY('pthreadpooltest',
                  source='tests.c',
                  deps='''PTHREADPOOL
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS
samba-util popt POPT_SAMBA ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth winbind-client RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug krb5samba authkrb5 krb5samba
''',
                  enabled=bld.env.WITH_PTHREADPOOL,
                  install=False)

bld.SAMBA_BINARY('pthreadpooltest_cmocka',
                  source='tests_cmocka.c',
                  deps='''PTHREADPOOL cmocka
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS
samba-util popt POPT_SAMBA ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth winbind-client RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug krb5samba authkrb5 krb5samba
''',
                  ldflags='-Wl,--wrap=pthread_create',
                  enabled=bld.env.WITH_PTHREADPOOL and bld.env['HAVE_LDWRAP'],
                  install=False)
