#!/usr/bin/env python

names = ['testsmbc',
         'testacl',
         'testacl2',
         'testacl3',
         'testbrowse',
         'testbrowse2',
         'testnotify',
         'teststat',
         'teststat2',
         'teststat3',
         'teststatvfs',
         'testfstatvfs',
         'testtruncate',
         'testchmod',
         'testutime',
         'testread',
         'testwrite',
         'testctx']

for name in names:
    bld.SAMBA_BINARY(name,
                     source='%s.c' % name,
                     deps='''popt smbclient
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS gse   CMDLINE_S3 secrets3 cli_cldap MESSAGING smbldap smbldaphelper pdb printing_migrate samba-passdb libcli_netlogon3 libsmb cli_spoolss ads cluster
samba-util popt  ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug talloc_report_printf dcerpc-pkt-auth krb5samba authkrb5 krb5samba common_auth npa_tstream msrpc3 auth libcli_lsa3  netapi trusts_util xattr_tdb
''',
                     install=False)
