#!/usr/bin/env python

bld.SAMBA_LIBRARY('dsdb-module',
	source=[],
	deps='DSDB_MODULE_HELPERS DSDB_MODULE_HELPER_RIDALLOC',
	private_library=True,
	grouping_library=True)

bld.SAMBA_SUBSYSTEM('DSDB_MODULE_HELPERS',
	source='util.c acl_util.c schema_util.c netlogon.c',
	autoproto='util_proto.h',
	deps='ldb ndr samdb-common samba-security'
	)

bld.SAMBA_SUBSYSTEM('DSDB_MODULE_HELPER_RIDALLOC',
	source='ridalloc.c',
	autoproto='ridalloc.h',
	deps='MESSAGING',
	)

# Build the cmocka unit tests
bld.SAMBA_BINARY('test_unique_object_sids',
        source='tests/test_unique_object_sids.c ../../../..//lib/async_req/async_sock.c ../../../..//lib/crypto/gnutls_error.c',
        deps='''
            talloc
            samdb
            cmocka
            DSDB_MODULE_HELPERS
            replace
            samba-util
            ndr-standard
            NDR_LSA
            NDR_DNSP
            NDR_SPOOLSS
samba-util popt CMDLINE_S4 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA
        ''',
        for_selftest=True)
bld.SAMBA_BINARY('test_encrypted_secrets_tdb',
        source='tests/test_encrypted_secrets.c  ../../../..//lib/async_req/async_sock.c ../../../..//lib/crypto/gnutls_error.c',
        cflags='-DTEST_BE=\"tdb\"',
        deps='''
            talloc
            samba-util
            samdb-common
            samdb
            cmocka
            gnutls
            DSDB_MODULE_HELPERS
            ndr-standard
            NDR_LSA
            NDR_DNSP
            NDR_SPOOLSS
samba-util popt CMDLINE_S4 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA
        ''',
        for_selftest=True)
if conf.env.HAVE_LMDB:
    bld.SAMBA_BINARY('test_encrypted_secrets_mdb',
            source='tests/test_encrypted_secrets.c ../../../..//lib/async_req/async_sock.c ../../../..//lib/crypto/gnutls_error.c',
            cflags='-DTEST_BE=\"mdb\"',
            deps='''
                talloc
                samba-util
                samdb-common
                samdb
                cmocka
                gnutls
                DSDB_MODULE_HELPERS
            ndr-standard
            NDR_LSA
            NDR_DNSP
            NDR_SPOOLSS
samba-util popt CMDLINE_S4 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA
            ''',
            for_selftest=True)

if bld.AD_DC_BUILD_IS_ENABLED():
    bld.PROCESS_SEPARATE_RULE("server")
