#! /bin/sh -e

set -e

if [ "$1" = purge ]; then

	if [ -e /usr/share/debconf/confmodule ]; then
		. /usr/share/debconf/confmodule
		db_purge
	fi

	if [ "$(readlink /etc/systemd/system/samba-ad-dc.service)" = '/dev/null' ]; then
		# Remove masking done by postinst (#832352)
		rm /etc/systemd/system/samba-ad-dc.service
	fi

	if [ -f /etc/apparmor.d/samba/smbd-shares ]; then
		rm /etc/apparmor.d/samba/smbd-shares
	fi
fi

#DEBHELPER#
