#!/usr/bin/env python

bld.SAMBA_LIBRARY('cli-ldap-common',
                  source='ldap_message.c ldap_ndr.c',
                  public_deps='samba-errors talloc ldb',
                  private_headers='ldap_message.h ldap_errors.h ldap_ndr.h',
                  deps='samba-util asn1util NDR_SECURITY tevent',
                  private_library=True)

bld.SAMBA_BINARY(
    'test_ldap_message',
    source='tests/ldap_message_test.c',
    deps='''
        cmocka
        talloc
        ldb
        samba-util
        asn1util
        NDR_SECURITY
        cli-ldap
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS
samba-util popt CMDLINE_S3 ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth winbind-client RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug talloc_report_printf dcerpc-pkt-auth
''',
    for_selftest=True
)
