#!/usr/bin/env python

bld.SAMBA3_BINARY('nmbd',
                 source='''
                 asyncdns.c
                 nmbd.c
                 nmbd_become_dmb.c
                 nmbd_become_lmb.c
                 nmbd_browserdb.c
                 nmbd_browsesync.c
                 nmbd_elections.c
                 nmbd_incomingdgrams.c
                 nmbd_incomingrequests.c
                 nmbd_lmhosts.c
                 nmbd_logonnames.c
                 nmbd_mynames.c
                 nmbd_namelistdb.c
                 nmbd_namequery.c
                 nmbd_nameregister.c
                 nmbd_namerelease.c
                 nmbd_nodestatus.c
                 nmbd_packets.c
                 nmbd_processlogon.c
                 nmbd_responserecordsdb.c
                 nmbd_sendannounce.c
                 nmbd_serverlistdb.c
                 nmbd_subnetdb.c
                 nmbd_winsproxy.c
                 nmbd_winsserver.c
                 nmbd_workgroupdb.c
                 nmbd_synclists.c
                 ''',
                 deps='''
                 talloc
                 tevent
                 smbconf
                 libsmb
                 CMDLINE_S3
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS gse  secrets3 cli_cldap MESSAGING smbldap smbldaphelper pdb printing_migrate samba-passdb libcli_netlogon3 libsmb cli_spoolss ads cluster stable_sort
samba-util popt ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth  RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug talloc_report_printf dcerpc-pkt-auth krb5samba authkrb5 krb5samba common_auth npa_tstream msrpc3 auth libcli_lsa3  netapi trusts_util xattr_tdb
                 ''',
                 install_path='${SBINDIR}')
