#!/usr/bin/env python

bld.SAMBA_SUBSYSTEM('NDR_NBT_BUF',
	source='nbtname.c',
	deps='talloc',
	autoproto='nbtname.h'
	)

bld.SAMBA_SUBSYSTEM('lmhosts',
                    source='lmhosts.c',
                    deps='replace talloc'
                    )

bld.SAMBA_LIBRARY('cli-nbt',
                  source='nbtsocket.c namequery.c nameregister.c namerefresh.c namerelease.c',
                  public_deps='ndr ndr_nbt tevent tevent-util NDR_SECURITY samba_socket samba-util lmhosts',
                  private_library=True
                  )

bld.SAMBA_BINARY('nmblookup' + bld.env.suffix4,
                 source='tools/nmblookup.c',
                 manpages='man/nmblookup4.1',
                 deps='''samba-hostconfig samba-util cli-nbt popt POPT_SAMBA netif LIBCLI_RESOLVE
ndr-standard NDR_LSA NDR_DNSP NDR_SPOOLSS
samba-util popt POPT_SAMBA ndr-table samba-errors NDR_DCERPC replace samba-debug NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_WITNESS NDR_SMBXSRV NDR_FSRVP NDR_IDMAP NDR_MDSSVC NDR_SPOOLSS NDR_NEGOEX ndr-standard ndr_nbt tdb util_tdb sys_rw time-basic socket-blocking server-role genrand ndr-krb5pac asn1util smbconf dbwrap messages_dgm msghdr tevent tevent-util samba3-util util_reg iov_buf interfaces util_setid cli_smb_common samba-cluster-support LIBTSOCKET CHARSET3 server_id_db smbd_shim messages_util tdb-wrap3 tdb-wrap talloc_report ldb samdb-common cli-ldap-common flag_mapping SAMDB_SCHEMA cliauth winbind-client RPC_NDR_WINREG dcerpc dcerpc-binding http gensec LIBCLI_SMB_COMPOSITE wbclient samdb smb_transport common_auth samba-modules LP_RESOLVE MESSAGING_SEND cli-ldap clidns replace dcerpc-samba samba-debug 
''',
                 install=False
                 )

bld.SAMBA_PYTHON('python_netbios',
                 source='pynbt.c',
                 public_deps='cli-nbt DYNCONFIG samba-hostconfig',
                 realname='samba/netbios.so'
                 )

